pawprints/urls.py
from profile.views import user_logout

from django.urls import re_path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.template.response import TemplateResponse
from django.views.decorators.csrf import csrf_exempt

from auth.views import CompleteAuthView, InitAuthView, MetadataView
from petitions import views


def handler500(request):
    context = {'request': request}
    template_name = '500.html'
    return TemplateResponse(request, template_name, context, status=500)


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^about/', views.about, name='about'),
    re_path(r'committees/', views.committees, name='committees'),
    re_path(r'^news/', views.news, name='news'),
    re_path(r'^admin/login', InitAuthView.as_view(), name='init-auth'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^acs$', csrf_exempt(CompleteAuthView.as_view()), name='acs'),
    re_path(r'^saml$', MetadataView.as_view(), name='metadata'),
    re_path(r'^login/', InitAuthView.as_view(), name='init-auth'),
    re_path(r'^logout/', user_logout, name='user_logout'),
    re_path(r'^petition/', include('petitions.urls')),
    re_path(r'^profile/', include('profile.urls')),
    re_path(r'^maintenance/', views.maintenance),
    re_path(r'^petitions/(?P<petition_id>\w+)$', views.petition_redirect)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

profile/urls.py
from django.urls import re_path
from . import views

app_name = 'profile'

urlpatterns = [
    re_path(r'^$', views.profile),
    re_path(r'^settings/notifications/staff/(?P<username>\w+)$', views.update_staff_emailing, name='staff_notification'),
    re_path(r'^settings/notifications/(?P<user_id>\d+)$', views.update_notifications, name='notification_update'),
    re_path(r'^manage/admin/alert/', views.update_alert, name='alert_update'),
    re_path(r'^manage/admin/add/(?P<user_id>\d+)$', views.add_superuser),
    re_path(r'^manage/admin/remove/(?P<user_id>\d+)$', views.remove_superuser),
    re_path(r'^manage/manager/add/(?P<user_id>\d+)$', views.add_staff_member),
    re_path(r'^manage/manager/remove/(?P<user_id>\d+)$', views.remove_staff_member),
    re_path(r'^manage/admin/', views.admin),
]

profile/models.py
"""
models.py
Peter Zujko (pxz3370)
Lukas Yelle (lxy5611)
10/20/16
Update: Nov 18 2016
"""
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Extends User model. Defines sn and notifications for a User.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.TextField()
    notifications = models.ForeignKey('profile.Notifications', on_delete=models.CASCADE)
    subscriptions = models.ManyToManyField('petitions.Petition', related_name='profile_subscriptions', blank=True)
    petitions_created = models.ManyToManyField('petitions.Petition', related_name='profile_petitions_created', blank=True)
    petitions_signed = models.ManyToManyField('petitions.Petition', related_name='profile_petitions_signed', blank=True)
    display_name = models.CharField(max_length=3, blank=True)
    # 0 - Does not have access, 1 - Has Access
    has_access = models.PositiveSmallIntegerField(default=1)

    def __unicode__(self):
        return self.user.username


# Defines user's email notification settings.
class Notifications(models.Model):
    update = models.BooleanField(default=True)
    response = models.BooleanField(default=True)
    reported = models.BooleanField(default=False)
    threshold = models.BooleanField(default=False)


# Defines the model for an app-wide, after login, popup on user clients
class GlobalAlert(models.Model):
    active = models.BooleanField(default=True)
    content = models.TextField()


# 
# The following functions define signals so that the Profile model 
# will be automatically created/updated whenever the Django User object 
# is created/updated. This makes it so you never have to call the Profile
# object's save method, all saving is done with the User model.
#
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **__):
    if created:
        Profile.objects.create(user=instance, notifications=Notifications.objects.create())


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **__):
    instance.profile.save()
    instance.profile.notifications.save()

profile/views.py
"""
Author: Peter Zujko (@zujko)
Description: Handles views and endpoints for all profile related operations.
Date Created: Nov 7 2016
Updated: Feb 16 2018
"""
import logging

from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Q
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST

from .models import Profile
from profile.models import GlobalAlert

logger = logging.getLogger("pawprints." + __name__)

CONFIG = settings.CONFIG


@login_required
def profile(request):
    """ Handles displaying information about the user
    and option to update their settings.
    """
    profile = Profile.objects.get(user=request.user)
    data_object = {
        'first_name': profile.user.first_name,
        'last_name': profile.user.last_name,
        'email': profile.user.email,
        'uid': profile.user.id,
        'notification_settings': profile.notifications,
        'petitions_created': profile.petitions_created.filter(~Q(status=2)),
        'main_logo': CONFIG['main_logo'],
        'analytics_id': settings.ANALYTICS,
        'name': CONFIG['name'],
        'generate_top_nav': CONFIG['generate_top_nav']
    }
    return render(request, 'profile.html', data_object)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def admin(request):
    """
    Handles displaying the staff managing panel.
    User must be logged in and a superuser.
    """
    profile = Profile.objects.get(user=request.user)
    superusers = User.objects.filter(is_superuser=True)
    superusers_id = superusers.values("id")

    alert, created = GlobalAlert.objects.get_or_create(id=1, defaults={'active': 'False', 'content': 'Placeholder alert content.'})

    report_user_profiles = Profile.objects.filter(notifications__reported=True).distinct("id")
    report_users = [prof.user for prof in report_user_profiles]
    threshold_user_profiles = Profile.objects.filter(notifications__threshold=True).distinct("id")
    threshold_users = [prof.user for prof in threshold_user_profiles]

    data_object = {
        'superusers': superusers,
        'staff': User.objects.filter(is_staff=True).exclude(id__in=superusers_id),
        'all_users': User.objects.all(),
        'main_logo': CONFIG['main_logo'],
        'generate_top_nav': CONFIG['generate_top_nav'],
        'analytics_id': settings.ANALYTICS,
        'name': CONFIG['name'],
        'alert': alert,
        'reportUsers': report_users,
        'thresholdUsers': threshold_users,
    }
    return render(request, 'admin.html', data_object)

# ENDPOINTS #


@require_POST
@login_required
def add_superuser(request, user_id):
    if request.user.is_superuser:
        if user_id is not None:
            user = User.objects.get(id=int(user_id))
            user.is_superuser = True
            user.is_staff = True
            user.save()
            return HttpResponse(True)
    return HttpResponseForbidden(False)


@require_POST
@login_required
def add_staff_member(request, user_id):
    if request.user.is_superuser:
        if user_id is not None:
            user = User.objects.get(id=int(user_id))
            user.is_staff = True
            user.save()
            return HttpResponse(True)
    return HttpResponseForbidden(False)


@require_POST
@login_required
def remove_superuser(request, user_id):
    if request.user.is_superuser:
        if user_id is not None:
            user = User.objects.get(id=int(user_id))
            user.is_superuser = False
            user.save()
            return HttpResponse(True)
    return HttpResponseForbidden(False)


@require_POST
@login_required
def remove_staff_member(request, user_id):
    if request.user.is_superuser:
        if user_id is not None:
            user = User.objects.get(id=int(user_id))
            user.is_staff = False
            user.save()
            return HttpResponse(True)
    return HttpResponseForbidden(False)


@require_POST
@login_required
def update_alert(request):
    if request.user.is_superuser:
        post = request.POST
        active = True if post.get('alert-active') == 'on' else False
        content = post.get('alert-content')
        alert, created = GlobalAlert.objects.get_or_create(id=1, defaults={'active': active, 'content': content})
        alert.active = active
        alert.content = content
        alert.save()
        return HttpResponse(True)
    return HttpResponseForbidden(False)


@require_POST
@login_required
def update_notifications(request, user_id):
    """ Handles updating a users
    notification settings.
    """
    if request.user.id != int(user_id):
        return HttpResponse(False)

    user = request.user

    user.profile.notifications.update = True if "updates" in request.POST else False
    user.profile.notifications.response = True if "response" in request.POST else False

    user.save()
    return HttpResponse(True)


@require_POST
@login_required
def update_staff_emailing(request, username):
    """ Handles updating a users
    notification settings.
    """
    if request.user.is_superuser:
        user = User.objects.get(username=username)
        if user:
            emailing_setting = request.POST.get('email-setting')
            emailing_value = request.POST.get('email-value')
            if emailing_setting == 'report':
                user.profile.notifications.reported = True if emailing_value == 'true' else False
            elif emailing_setting == 'threshold':
                user.profile.notifications.threshold = True if emailing_value == 'true' else False
            else:
                return HttpResponse(False)
            user.save()
            return HttpResponse(True)
    return HttpResponse(False)


@login_required
def user_logout(request):
    """ Handles logging a user out
    """
    logout(request)
    url_next = request.GET.get('next', '/')
    return redirect(url_next)

profile/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load compress %}
    {% load static %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/switchery/0.8.2/switchery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/switchery/0.8.2/switchery.min.css">
    {% include 'head.html' with analytics_id=analytics_id %}
    <title>Account | {{ name }}</title>

    {% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/profile.css' %}">
    {% endcompress %}
</head>
<body>

<div id="wrapper">
    {% include 'header.html' with main_logo=main_logo generate_top_nav=generate_top_nav name=name %}
    <main class="full-width">
        <section id="landing" class="text-center overflow-hidden">
            <h1>{{ first_name }} {{ last_name }}</h1>
            <h5>{{ email }}</h5>
        </section>
        <section id="sub-landing" class="ninety-width">
            <form id="settings" name="settings" method="post" action="{% url 'profile:notification_update' user_id=uid %}">
                {% csrf_token %}
                <ul class="list">
                    <li class="list-item block padding overflow-hidden">
                        <label class="block left ninety-width padding cursor" for="updates">
                            E-mail me when new status updates are petitioned on petitions I sign
                        </label>
                        <div class="right padding-right padding-top">
                            <input id="updates" class="js-switch" type="checkbox" name="updates" {% if notification_settings.update %} checked="checked" {% endif %}>
                        </div>
                    </li>
                    <li class="list-item block padding overflow-hidden">
                        <label class="block left ninety-width padding cursor" for="response">
                            E-mail me when an official response is petitioned on a petition I sign.
                        </label>
                        <div class="right padding-right padding-top">
                            <input id="response" class="js-switch " type="checkbox" name="response" {% if notification_settings.response %} checked="checked" {% endif %}>
                        </div>
                    </li>
                    <li class="list-item block padding overflow-hidden">
                        <label class="block left ninety-width padding cursor" for="response">
                            Turn on PawPrints Dark Mode.
                        </label>
                        <div class="right padding-right padding-top">
                            <input id="response" class="js-switch " type="checkbox" name="response" {% if notification_settings.darkmode %} checked="checked" {% endif %} (click)="darkmode()">
                        </div>
                    </li>
                </ul>
            </form>
        </section>
        <section>
            <div class="ninety-width">
                {% if petitions_created.count > 0 %}
                    <h1>Petitions Created</h1>
                    {% for petition in petitions_created %}
                        <article class="padding white-background cursor" onclick="window.location.href='/?p={{petition.id}}'">
                            <h3 class="text-highlight capitalize inline-block">{{ petition.title }}</h3>
                            {% if petition.status == 0 %}
                                <p class="inline-block margin-left italics">Not Published</p>
                                <p class="right">
                                    <a href="/petition/unpublish/{{petition.id}}" class="delete-petition material-icon-container modern-link cursor margin-right">Delete
                                        <i class="material-icons">delete</i>
                                    </a>
                                </p>
                            {% else %}
                                <p class="inline-block margin-left">Published</p>
                                <p class="inline-block margin-left">{{petition.signatures}} / 200 Signatures</p>
                            {% endif %}
                        </article>
                    {% endfor %}
                {% endif %}
            </div>
        </section>
    </main>
</div>

<script>
    $(document).ready(function(){

        window.plugins = {
            "switchery":[]
        };
        var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
        elems.forEach(function(html) {
            window.plugins.switchery.push(new Switchery(html,{size:"small"}));
        });
        $("#settings").find("input").change(function(){

            var form = $(this).closest("form");

            $.post(form.attr("action"), form.serialize(),function(r){
                if(!r){
                    console.log("Error saving user preferences. User sent does not matched logged in user.");
                }
            });

        });

    });

    $(document).ready(function darkmode(){
        document.documentElement.style.setProperty('--navbackground', "lightblue");
    })
</script>

</body>
</html>